import {
  AlertTriangle,
  ArrowRight,
  CheckCircle,
  ChevronDownIcon,
  Clock,
  Edit,
  Eye,
  Facebook,
  Globe,
  Info,
  Instagram,
  LayoutGrid,
  Linkedin,
  Loader,
  LogIn,
  Mail,
  MapIcon,
  Phone,
  Play,
  PlayCircleIcon,
  Rocket,
  Search,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Star,
  Twitter,
  UserPen,
  X,
  XCircle,
  Youtube,
} from 'lucide-react';

export const PAGE_ICONS = {
  ARROWRIGHT: ArrowRight,
  ROCKET: Rocket,
  SHIELDCHECK: ShieldCheck,
  SPARKLES: Sparkles,
  STAR: Star,

  //Toast Icons
  CHECKCIRCLE: CheckCircle,
  XCIRCLE: XCircle,
  ALERTTRIANGLE: AlertTriangle,
  INFO: Info,
  LOGIN: LogIn,
  MAP: MapIcon,
  PLAYCIRCLE: PlayCircleIcon,
  PLAY: Play,
  CLOCK: Clock,
  VIEWS: Eye,
  EDIT: UserPen,
  CANCLE: X,

  //Navbar icons
  CART: ShoppingCart,
  XMARK: XCircle,
  SEARCH: Search,
  GRID: LayoutGrid,
  DOWN: ChevronDownIcon,

  //Social icons
  FACEBOOK: Facebook,
  INSTAGRAM: Instagram,
  YOUTUBE: Youtube,
  TWITTER: Twitter,
  LINKEDIN: Linkedin,
  PHONE: Phone,
  MAIL: Mail,
  BROWSER: Globe,
};
